/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  safelist: [
    'bg-background',
    'bg-card',
    'bg-popover',
    'bg-primary',
    'bg-secondary',
    'bg-muted',
    'bg-accent',
    'bg-destructive',
    'bg-success',
    'bg-warning',
    'text-foreground',
    'text-primary',
    'text-secondary',
    'text-muted',
    'text-accent',
    'text-destructive',
    'text-primary-foreground',
    'text-secondary-foreground',
    'text-success-foreground',
    'text-warning-foreground',
    'text-destructive-foreground',
    'text-muted-foreground',
    'text-accent-foreground',
    'hover:bg-primary/90',
    'hover:bg-secondary/80',
    'hover:bg-success/90',
    'hover:bg-warning/90',
    'hover:bg-destructive/90',
    'hover:bg-accent/90',
    'border-border',
    'border-primary',
    'border-secondary',
    'border-muted',
    'border-accent',
    'border-destructive',
  ],
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        success: {
          DEFAULT: "hsl(var(--success))",
          foreground: "hsl(var(--success-foreground))",
        },
        warning: {
          DEFAULT: "hsl(var(--warning))",
          foreground: "hsl(var(--warning-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} 