/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  safelist: [
    'bg-background',
    'bg-card',
    'bg-popover',
    'bg-primary',
    'bg-secondary',
    'bg-muted',
    'bg-accent',
    'bg-destructive',
    'bg-success',
    'bg-warning',
    'bg-brand-primary',
    'bg-brand-secondary',
    'bg-brand-accent',
    'text-foreground',
    'text-primary',
    'text-secondary',
    'text-muted',
    'text-accent',
    'text-destructive',
    'text-primary-foreground',
    'text-secondary-foreground',
    'text-success-foreground',
    'text-warning-foreground',
    'text-destructive-foreground',
    'text-muted-foreground',
    'text-accent-foreground',
    'text-brand-primary',
    'text-brand-secondary',
    'text-brand-accent',
    'hover:bg-primary/90',
    'hover:bg-secondary/80',
    'hover:bg-success/90',
    'hover:bg-warning/90',
    'hover:bg-destructive/90',
    'hover:bg-accent/90',
    'hover:bg-brand-primary/90',
    'hover:bg-brand-secondary/80',
    'border-border',
    'border-primary',
    'border-secondary',
    'border-muted',
    'border-accent',
    'border-destructive',
    'border-brand-primary',
    'border-brand-secondary',
  ],
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        success: {
          DEFAULT: "hsl(var(--success))",
          foreground: "hsl(var(--success-foreground))",
        },
        warning: {
          DEFAULT: "hsl(var(--warning))",
          foreground: "hsl(var(--warning-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        // Enhanced Brand Colors for Dropr
        brand: {
          50: "#FDF8F3",
          100: "#F7EDE1", 
          200: "#EAD4B8",
          300: "#D4A96E",
          400: "#B6834F",
          500: "#614E41", // Primary brand color
          600: "#4A3A2F",
          700: "#3A2C23",
          800: "#2A1F18",
          900: "#1A1410",
          950: "#0F0A08",
        },
        // Extended Neutral Palette
        neutral: {
          0: "#FFFFFF",
          50: "#FAFAFA",
          100: "#F5F5F5",
          200: "#E5E5E5",
          300: "#D4D4D4",
          400: "#A3A3A3",
          500: "#737373",
          600: "#525252",
          700: "#404040",
          800: "#262626",
          900: "#171717",
          950: "#0A0A0A",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}